---
  - name: Print os facts
    hosts: all
    tasks:
      - name: Print OS
        debug:
          msg: "{{ ansible_distribution }}"
      - name: Print fact
        debug:
          msg: "{{ some_fact }}"
  - name: Print any fedora vars
    hosts: fed
    tasks:  
      - name: Print fedora var
        debug:
          msg: "{{ any_variable }}"